# Generated by Django 2.2.3 on 2019-07-10 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangitUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subdjangit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('about', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('moderator', models.ForeignKey(default='djangit.DjangitUser.objects.username', on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='djangit.DjangitUser')),
                ('subscribers', models.ManyToManyField(blank=True, to='djangit.DjangitUser')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangit.DjangitUser')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticed', models.BooleanField(default=False)),
                ('notify_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangit.DjangitUser')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangit.Post')),
            ],
        ),
        migrations.AddField(
            model_name='djangituser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='djangit.Subdjangit'),
        ),
        migrations.AddField(
            model_name='djangituser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
