# Generated by Django 2.2.3 on 2019-07-10 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdjangit',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='djangit.DjangitUser'),
        ),
    ]
