# Generated by Django 2.2.3 on 2019-07-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangituser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='djangit.DjangitUser'),
        ),
    ]
