# Generated by Django 2.2.3 on 2019-07-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangit', '0002_auto_20190716_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
