# Generated by Django 2.2.3 on 2019-07-03 22:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangit', '0003_notification_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdjangit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('about', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscribers', models.ManyToManyField(blank=True, to='djangit.DjangitUser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djangit.DjangitUser')),
            ],
        ),
    ]
