# Generated by Django 2.2.3 on 2019-07-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangit', '0003_post_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
    ]
