# Generated by Django 2.2.3 on 2019-07-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangit', '0004_remove_post_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
