# Generated by Django 2.2.3 on 2019-07-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangit', '0004_subdjangit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangituser',
            name='following',
        ),
        migrations.RemoveField(
            model_name='subdjangit',
            name='user',
        ),
        migrations.AddField(
            model_name='djangituser',
            name='moderator',
            field=models.ManyToManyField(blank=True, related_name='moderator', to='djangit.Subdjangit'),
        ),
        migrations.AddField(
            model_name='djangituser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='djangit.Subdjangit'),
        ),
    ]
