# Generated by Django 2.2.3 on 2019-07-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangit', '0005_post_total_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='total_votes',
        ),
    ]
