# Generated by Django 2.2.3 on 2019-07-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangit', '0002_auto_20190711_2345'),
        ('djangit', '0006_remove_post_total_votes'),
    ]

    operations = [
    ]
