# Generated by Django 2.2.3 on 2019-07-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangit', '0006_auto_20190710_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdjangit',
            name='url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
