# Generated by Django 2.2.3 on 2019-07-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangit', '0006_auto_20190710_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdjangit',
            name='title',
            field=models.CharField(default='', max_length=25),
        ),
    ]
