# Generated by Django 2.2.3 on 2019-07-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangit', '0007_merge_20190715_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
